### PR TITLE
Add Silkky.Cloud to Privacy

### PR DESCRIPTION
**Pull request by TheSilkky**
Add Silkky.Cloud to Privacy

- [x] I have referred the list and did not find this submission already added.
- [x] I have read the contribution guidelines [here](https://github.com/humanetech-community/awesome-humane-tech/blob/main/contributing.md)
- [x] I have read the code of conduct and I agree to adhere to the same [here](https://github.com/humanetech-community/awesome-humane-tech/blob/main/code-of-conduct.md)
- [x] I have added my entry as the latest (last dotted point) under a topic, not at the beginning, not interleaved. 

If your suggested entry is code project:

- [x] I have checked that the project is open source and has a [FSF-approved](https://www.gnu.org/licenses/license-list.html) license.

 

### Explain why it's a Humane Technology: 

Silkky.Cloud hosts many of the open-source, privacy respecting web applications listed on awesome-humane-tech such as:
- [Searx](https://searx.silkky.cloud/)
- [Invidious](https://invidious.silkky.cloud/)
- [Bitwarden](https://vault.silkky.cloud/)
- [And more..](https://www.silkky.cloud/)

All services are hosted in Finland. None of these services track users or share any personal data with third parties.
- [Privacy Policy](https://www.silkky.cloud/privacy)
- [Terms of Service](https://www.silkky.cloud/tos)

### Sourcecode is available at :  
 

- [Website source](https://github.com/silkkycloud/silkky.cloud) - **AGPLv3 or later**
- [Other](https://github.com/silkkycloud)

### Is there a similar software/tool etc., that already exists?

No : The primary goal of Silkky.Cloud is too host high availability, privacy-respecting web services that protect users against global surveillance, without comprising on usability.
  
### Add any other topic/section here you wish to explain and elaborate

Making our own open-source web services is a priority.

### CODE REVIEW

**Comment by aschrijver** [comment]
Thank you for this PR.

I have to take this into consideration. Silkky is different than other entries that are projects on their own, in that you provide bundled services. It is not a typical entry, and also you just started.. so that makes it harder for me to gauge 'awesomeness' atm, if you get what I mean.

I will leave this PR open for a while. There is a lot of interest in bundled service offerings of FOSS software. As long as these can be self-hosted and are entirely made with (F)OSS there may a place for them on this list. But in that case in a new list section "Bundled Services" or something.

**Comment by TheSilkky** [comment]
Adding a new category and waiting a little while would be appropriate, thanks for the response.

**Comment by aschrijver** [comment]
Closing this for now, and keep #78 open instead until I made a decision.

**Comment by aschrijver** [comment]
As per #78 the new location for projects like these - and including Silkky.Cloud - is: https://codeberg.org/jonatasbaldin/delightful-libre-hosters

**Pull request closed without merging**
