### PR TITLE
Add personalDNSfilter

### PR DESCRIPTION
**Pull request by smed79**

### CODE REVIEW

**Comment by aschrijver** [comment]
Thank you for your PR!

There are two improvements to make before I can merge:

- New entries must be added as last on the bottom of their category.
- The first link should be to the site: https://www.zenz-solutions.de/personaldnsfilter-wp/ not twice to the repo.

**Comment by smed79** [comment]
@aschrijver To avoid noise, please edit from your side.
I accidentally deleted my branch.

Thank you.

**Comment by aschrijver** [comment]
:+1: 

Closing, replaced by https://github.com/humanetech-community/awesome-humane-tech/commit/4c2288d17e36b8355ef456c96ba75605a3962951

**Comment by smed79** [comment]
Thank you.

**Pull request closed without merging**
