### PR TITLE
Add LibRedirect

### PR DESCRIPTION
**Pull request by alefvanoon**
- [x] I have referred the list and did not find this submission already added.
- [x] I have read the contribution guidelines [here](https://github.com/humanetech-community/awesome-humane-tech/blob/main/contributing.md)
- [x] I have read the code of conduct and I agree to adhere to the same [here](https://github.com/humanetech-community/awesome-humane-tech/blob/main/code-of-conduct.md)
- [x] I have added my entry as the latest (last dotted point) under a topic, not at the beginning, not interleaved. 

If your suggested entry is code project:

- [x] I have checked that the project is open source and has a [FSF-approved](https://www.gnu.org/licenses/license-list.html) license.

 

### Name of my software/tool/service/technology/project : 
LibRedirect
### Explain why it's a Humane Technology: { }
A simple extension that redirects to alternative privacy-friendly frontends.
### Is there a similar software/tool etc., that already exists?

Yes : It's fork off Privacy-redirect. Its development had stopped. we are develop & adding some feature like instance list updator.

### CODE REVIEW

**Comment by aschrijver** [comment]
Thank you, nice initiative. Could you move this to the "Social Networks" category instead, then I'll merge it there. Privacy Redirect exists there too, and the category has mostly social network-related tools (rather than full-blown social networks).

**Comment by alefvanoon** [comment]
Ok, but this extentions is not just for Social Networks!

**Comment by aschrijver** [comment]
Thank you. Yes, I know. A couple of things would benefit from a cleanup if I find the time for it :)

**Comment by aschrijver** [comment]
PS. A good place to name-drop your project on HN front page right now: https://news.ycombinator.com/item?id=30114322

**Comment by alefvanoon** [comment]
Thanks for your suggestion.

**Pull request merged**
