### PR TITLE
Added QuickTwit

### PR DESCRIPTION
**Pull request by qualityjacks**

### CODE REVIEW

**Comment by gkrishnaks** [comment]
Hi, thanks for willing to contribute to Humane Tech awesome list.

Can you please share these information in a format like this (+ add your own titles too) : 

1) "What is my tool about? Why I believe it's humane and ethical tech?"
2) Where is the sourcecode of the tool and under what license? If not a FLOSS/FOSS/OSS project, please clarify further.
3) How is it different from existing tools and why you are recommending it as Ethical Humane software? Or is it a new tool/new idea and similar one does not exist? 

When submitting a new entry to a section, can you raise PR by adding to the end of list on a topic, not at the beginning so that our list's history looks incrementally updated.

Every project in humanetech awesome list is equally important to welfare of our society and so we use dotted points and not numerical points to avoid implying the order.

Also see https://github.com/humanetech-community/awesome-humane-tech/blob/master/contributing.md

**Comment by qualityjacks** [comment]
Hello,

Thank you for the quick response.


   1. My tool is about finding the latest trends in topics of interest, and
   from selective twitter accounts. I believe that the tool is ethical because
   we use content from twitter, and our algorithm gives us the results.
   2. It uses NLP and Data Science. It's not open source.
   3. It is different because other tools are location-based, and we are
   topic-based.

Please let me know if you need any more information.

Thank you,
Vikas

**Comment by aschrijver** [comment]
Hi @qualityjacks unfortunately your tool not being open-source does not make it suitable for inclusion in this curated list. I am sorry.

**Comment by qualityjacks** [comment]
Thank you for the reply, Arnold, it's alright :)

**Pull request closed without merging**
