### PR TITLE
Add Self Harm Detector

### PR DESCRIPTION
**Pull request by jonathanloos**
Would love to add this small ruby gem to your list!

- [x] I have referred the list and did not find this submission already added.
- [x] I have read the contribution guidelines [here](https://github.com/humanetech-community/awesome-humane-tech/blob/main/contributing.md)
- [x] I have added my entry as the latest (last dotted point) under a topic, not at the beginning, not interleaved.
- [x] I have verified that my entry fits a single line in the list (based on the maximum column width Github uses).

If your suggested entry is code project:

- [x] I have checked that the project is open source and has a [FSF-approved](https://www.gnu.org/licenses/license-list.html) license.

 

### Name of my software/tool/service/technology/project : 
Self Harm Detector

### Explain why it's a Humane Technology: 
Self Harm Detector is a simple approach to identifying the intention of self-harm in text. This gem is intended to act as reference implementation that might be helpful in the identification of any sets of words or intentions within text. This gem in no way intends to provide a comprehensive method for identifying self-harm in text.

### Sourcecode is available at :
[Self Harm Detector Gihub](https://github.com/harled/self_harm_detector) - License MIT

### Is there a similar software/tool etc., that already exists?

Yes : how does my project differ from the existing one (also include how it differs in terms of humane ethical reasons?  

No : 
Based on our searching we could not find a great matching technology for what we've built. We're very excited to see what ideas the community has and see how the gem develops over time.

### CODE REVIEW

**Comment by KOLANICH** [comment]
It uses hardcoded phrases instead of machine learning models using word embeddings. I guess that even an average vector with knn will do better than this.

I think that this package makes more harm than good because it competes with packages that are more efficient than this approach.

**Comment by jonathanloos** [comment]
Hey @KOLANICH ! Thanks for your input, we totally recognize the gem is juvenile and in it's early stages. We wouldn't want to harm the community, and are open to suggestions. 

Do you have any suggestions on avenues we could pursue?

**Comment by KOLANICH** [comment]
As I have said, I think that you should use text summarization approaches to vectorize the input (the most primitive is an average vector of the word, more sophisticated approaches are neural networks, but I guess transformers are too heavy for this case, use so I guess LSTM/GRU) and then apply some classifier. I guess SVM may generalize even better than KNN for this case, so try it first. Or maybe a lightweight network. Then export it into ONNX and use libonnx or onnxruntime for inference. Warning: onnxruntime is the lib by M$ and contains telemetry.

**Comment by aschrijver** [comment]
Sorry for being late in reacting.. I have been busy. I share the view @KOLANICH provided. Given the early stage of the project and sensitive subject area I feel that, while its great to build helpful tools in this area, right now the project is no good fit for the list. I thank you for drafting though. And hope you'll understand me closing this PR for now.

**Pull request closed without merging**
