### PR TITLE
Add Mindful Google™

### PR DESCRIPTION
**Pull request by tunjos**
A Chrome extension that disables Autocomplete and other distracting elements on Google's pages.

- [x] I have referred the list and did not find this submission already added.
- [x] I have read the contribution guidelines [here](https://github.com/humanetech-community/awesome-humane-tech/blob/main/contributing.md)
- [x] I have read the code of conduct and I agree to adhere to the same [here](https://github.com/humanetech-community/awesome-humane-tech/blob/main/code-of-conduct.md)
- [x] I have added my entry as the latest (last dotted point) under a topic, not at the beginning, not interleaved. 

If your suggested entry is code project:

- [x] I have checked that the project is open source and has a [FSF-approved](https://www.gnu.org/licenses/license-list.html) license.

 

### Name of my software/tool/service/technology/project : 
Mindful Google™
### Explain why it's a Humane Technology: { }
It helps with mindfullness when using the Google Search Engine. It disables Autocomplete and other distracting elements on Google's pages.
### Sourcecode is available at :  
 
[Mindful-Google™](https://github.com/tunjos/Mindful-Google)
### Is there a similar software/tool etc., that already exists?
No: No extension so far helps to disable autocomplete on Google. This is a forced feature by Google. Some search engines like DuckDuckGo, Bing, etc. provide the possibility to completely disable autocomplete. Others like Google don't.  

### Add any other topic/section here you wish to explain and elaborate
Read more here...https://tunjos.co/blog/autocomplete-search-engine-can-be-evil/

### CODE REVIEW

**Comment by aschrijver** [comment]
Thanks for your PR!

It is a candidate for addition, even though it isn't very popular yet (but popularity is not the main criterium for considering something 'awesome' :smile: ).

I try to have entries fit a single line on the README here on Github. That is a rule, but it isn't documented well (there is an open issue for that). Your description is too long then.

Finally.. I consider moving this entire curated list away from Github altogether (this repo will then point to the new location). It will then become a [delightful list](https://codeberg.org/teaserbot-labs/delightful) on [Codeberg](https://codeberg.org) instead, and show on the [Delightful Club](https://delightful.club) website too. Note: I created delightful project as alternative to awesome that is only for FOSS, Open Data and Open Science related resources.

**Comment by tunjos** [comment]
> Your description is too long then.

Fixed. :)

Thanks for the hint and feedback by the way. **Delightful.Club** makes sense! And yes, I think there are lots of great projects that aren't FOSS. Cheers!

**Comment by aschrijver** [comment]
It is merged :smile: 

PS. What I forgot to mention. You have a dangerous naming to your project, that might lead to a takedown request, though IANAL. You may consider another name, e.g. "MindfulFind" or something.

**Comment by tunjos** [comment]
Awesome! Thanks! 🔥 
Thanks for the hint! Do you say this because of the **"Google"** Reference? @aschrijver

**Comment by aschrijver** [comment]
Mindful Google™ especially with the trademark attached can easily be confused or associated with Google itself, as something they created, support or endorse.

**Comment by tunjos** [comment]
@aschrijver  So from what I understand as regards the Software world, **™** signifies an **unregistered trademark** while  **®** signified a **registered trademark**. The former from what I know is used to show no ownership of the word(s) it appears after.

Here are popular extensions that have a similar naming:
- [Checker Plus for Google Calendar™
](https://chrome.google.com/webstore/detail/checker-plus-for-google-c/hkhggnncdpfibdhinjiegagmopldibha)
- [Read&Write for Google Chrome™](https://chrome.google.com/webstore/detail/readwrite-for-google-chro/inoeonmfapjbbkmdafoankkfajkcphgd)
- [Black Menu for Google™](https://chrome.google.com/webstore/detail/black-menu-for-google/eignhdfgaldabilaaegmdfbajngjmoke)
- [Screen Recorder for Google Chrome™
](https://chrome.google.com/webstore/detail/screen-recorder-for-googl/eclbecdgdoahkliaijlpkigldlkojjdn)

Cheers!✌🏾

**Pull request merged**
